/**
 * FayaNMS governed icon registry — types.
 *
 * `FayanmsIconName` is the closed set of custom FayaNMS SVG glyphs staged in
 * `public/icons/fayanms/*.svg` (24×24 viewBox, stroke currentColor). File
 * name = icon name (kebab-case, no extension).
 *
 * Lucide stays the source for generic controls/status chrome; custom glyphs
 * carry domain identity (nav domains, device types, vendors). See
 * `src/lib/icons/navigation-icons.ts`, `vendor-icons.ts` and
 * `device-icons.ts` for the governed mappings.
 */
import type { LucideIcon } from "lucide-react";

// Generated from public/icons/fayanms — keep in sync via scripts/validate-icon-registry.ts
export type FayanmsIconName =
  | "acknowledge"
  | "acl"
  | "action-add"
  | "action-backup-now"
  | "action-cancel"
  | "action-compare"
  | "action-copy"
  | "action-delete"
  | "action-download"
  | "action-edit"
  | "action-execute"
  | "action-export"
  | "action-filter"
  | "action-hide"
  | "action-import"
  | "action-lock"
  | "action-open"
  | "action-pause"
  | "action-refresh"
  | "action-restore"
  | "action-resume"
  | "action-revoke"
  | "action-rollback"
  | "action-rotate-secret"
  | "action-schedule"
  | "action-search"
  | "action-sync"
  | "action-terminal"
  | "action-test-connection"
  | "action-upload"
  | "action-validate"
  | "action-view"
  | "administration"
  | "ai-rca"
  | "alerts"
  | "all-changes"
  | "api"
  | "api-clients"
  | "approvals"
  | "arp-table"
  | "ask-network"
  | "audit"
  | "availability"
  | "backup-policy"
  | "backup-storage"
  | "backups"
  | "bandwidth"
  | "baselines"
  | "bgp"
  | "capacity"
  | "cdp"
  | "change-audit"
  | "change-calendar"
  | "change-correlation"
  | "change-templates"
  | "changes"
  | "checksum"
  | "cmdb"
  | "collector-rebalance"
  | "collectors"
  | "collectors-admin"
  | "command-palette"
  | "compliance"
  | "config-diff"
  | "config-viewer"
  | "configuration"
  | "configuration-encrypted"
  | "correlate"
  | "cpu"
  | "credentials"
  | "dashboard"
  | "density"
  | "device-cloud"
  | "device-drivers"
  | "device-firewall"
  | "device-generic"
  | "device-router"
  | "device-server"
  | "device-switch"
  | "devices"
  | "dhcp"
  | "discovery"
  | "dns"
  | "dns-server"
  | "download-config"
  | "drift"
  | "emergency-change"
  | "events"
  | "execute-change"
  | "export-csv"
  | "export-json"
  | "export-pdf"
  | "export-xlsx"
  | "failover-test"
  | "fan"
  | "fayanms-mark"
  | "fayanms-network-shield"
  | "fayanms-noc-mark"
  | "firewall-policy"
  | "firmware"
  | "flow-analytics"
  | "global-search"
  | "gnmi"
  | "health-score"
  | "help"
  | "high-availability"
  | "https"
  | "implementation-plan"
  | "incident-assignment"
  | "incident-timeline"
  | "incidents"
  | "integrations"
  | "interface-errors"
  | "interfaces"
  | "jobs"
  | "latency"
  | "licensing"
  | "link-aggregation"
  | "lldp"
  | "location"
  | "logs"
  | "mac-address"
  | "mac-table"
  | "maintenance"
  | "maintenance-window"
  | "management-ip"
  | "memory"
  | "metrics"
  | "my-changes"
  | "nat"
  | "nat-policy"
  | "neighbors"
  | "netconf"
  | "network"
  | "noc"
  | "normalize"
  | "notification-channels"
  | "notifications"
  | "ntp"
  | "operations"
  | "organizations"
  | "ospf"
  | "packet-loss"
  | "performance"
  | "permissions"
  | "post-incident-review"
  | "power"
  | "pre-check"
  | "predictive-health"
  | "profile"
  | "report-audit"
  | "report-availability"
  | "report-backup-compliance"
  | "report-builder"
  | "report-capacity"
  | "report-changes"
  | "report-drift"
  | "report-incidents"
  | "report-performance"
  | "reports"
  | "restconf"
  | "restore"
  | "retention"
  | "risk-assessment"
  | "roles"
  | "rollback"
  | "root-cause-analysis"
  | "routes"
  | "scheduled-reports"
  | "secret-mask"
  | "severity-critical"
  | "severity-high"
  | "severity-info"
  | "severity-low"
  | "severity-medium"
  | "site-building"
  | "site-rack"
  | "sites"
  | "sla"
  | "snapshots"
  | "snmp"
  | "ssh"
  | "static-route"
  | "status-approved"
  | "status-completed"
  | "status-compliant"
  | "status-danger"
  | "status-degraded"
  | "status-drift-detected"
  | "status-failed"
  | "status-info"
  | "status-maintenance"
  | "status-noncompliant"
  | "status-offline"
  | "status-online"
  | "status-pending"
  | "status-rejected"
  | "status-rollback-required"
  | "status-running"
  | "status-scheduled"
  | "status-success"
  | "status-unknown"
  | "status-unmanaged"
  | "status-warning"
  | "stp"
  | "suppress"
  | "syslog"
  | "system-settings"
  | "telemetry"
  | "temperature"
  | "theme"
  | "topology"
  | "trends"
  | "users"
  | "validation"
  | "vendor-cisco"
  | "vendor-fortigate"
  | "vendor-generic"
  | "vendor-hpe"
  | "vendor-juniper"
  | "vendor-palo-alto"
  | "vendor-sophos"
  | "vendors"
  | "vlan"
  | "vpn"
  | "webhook"
  | "webhooks"
  | "zero-touch-provisioning";

/**
 * Navigation glyph union: a sidebar entry carries either a Lucide component
 * (generic controls/status chrome — e.g. the chevron of a collapsible group)
 * or a governed FayaNMS domain glyph referenced by registry name.
 */
export type NavIcon =
  | { kind: "lucide"; icon: LucideIcon }
  | { kind: "fayanms"; name: FayanmsIconName };
