/**
 * Sandbox environment provisioning — regenerates the UNTRACKED secret files
 * after a sandbox reset (they never live in git):
 *
 *   .env                    — the Next.js control plane (app :3000)
 *   mini-services/worker/.env — the worker plane (:3030)
 *
 * Design constraints (documented in docs/review/STATE.md, wave 3):
 *   - Key generation happens IN-PROCESS and files are written DIRECTLY to
 *     disk — PEM material must never pass through shell variables (the
 *     sandbox secret-scrubber rewrites it in transit).
 *   - Two-plane EdDSA trust (P1-007): the CONTROL keypair signs app→worker
 *     tokens; the WORKER keypair signs worker→app tokens; each plane holds
 *     the OPPOSITE side's public key in FAYANMS_SERVICE_PUBLIC_KEYS.
 *   - Sandbox secrets use the SAME documented throwaway CI hex values as
 *     .github/workflows/ci.yml (no real secret ever lives here).
 *
 * Usage: bun scripts/provision-sandbox-env.ts [--force]
 */

import { generateKeyPairSync, randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PROJECT = join(import.meta.dir, "..");
const APP_ENV = join(PROJECT, ".env");
const WORKER_ENV = join(PROJECT, "mini-services", "worker", ".env");

const force = process.argv.includes("--force");

if (!force && (existsSync(APP_ENV) || existsSync(WORKER_ENV))) {
    console.error("Env files already exist — use --force to overwrite.");
    process.exit(1);
}

function keypair(): { privateSingleLine: string; publicBase64: string } {
    const { publicKey, privateKey } = generateKeyPairSync("ed25519");
    return {
        privateSingleLine: privateKey
            .export({ format: "pem", type: "pkcs8" })
            .toString("utf8")
            .trim()
            .replaceAll("\n", "\\n"),
        publicBase64: publicKey.export({ format: "der", type: "spki" }).toString("base64"),
    };
}

const control = keypair(); // minter on the app plane
const worker = keypair(); // minter on the worker plane

// Fresh per-run sandbox secrets — NEVER a committed/literal value: the
// startup security policy's known-bad blocklist (P1-019) refuses documented
// demo hex at boot, and gitleaks correctly keeps scripts/ under the full
// default ruleset (no literal fixture values belong in this tree).
const freshHex = (): string => randomBytes(32).toString("hex");
const nextAuthSecret = freshHex();
const configKek = freshHex(); // ONE envelope key shared by BOTH planes

// Cross-verified: each plane trusts the OTHER side's public key.
const appEnv = `# FayaNMS sandbox env — control plane (generated by scripts/provision-sandbox-env.ts)
# Every secret below is FRESH RANDOM per run — sandbox-only, never committed.

DATABASE_URL="postgresql://fayanms:fayanms@localhost:5433/fayanms"
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="${nextAuthSecret}"
NEXTAUTH_SESSION_SECRET="${freshHex()}"

# P1-007 two-plane EdDSA service identity — CONTROL keypair mints app→worker
FAYANMS_SERVICE_PRIVATE_KEY="${control.privateSingleLine}"
FAYANMS_SERVICE_PUBLIC_KEYS="${worker.publicBase64}"

# Config snapshot KEK (64 hex, random per run — shared with the worker plane)
FAYANMS_CONFIG_ENC_KEY="${configKek}"
FAYANMS_CONFIG_ENC_KEY_ID=k1

WORKER_BASE_URL="http://localhost:3030"

# Sandbox local sites (SSR origin per-request; F-026)
SITE_URL="http://localhost:3000"
`;

const workerEnv = `# FayaNMS sandbox env — worker plane (generated by scripts/provision-sandbox-env.ts)
# NOTE: no DATABASE_URL here — the worker never touches PostgreSQL (all
# persistence goes through the app API; SEC-ENV-001 per-service scopes).

PORT=3030

# P1-007 two-plane EdDSA service identity — WORKER keypair mints worker→app.
# The rotation list carries BOTH public halves: the CONTROL key (verifying
# app→worker calls) and THIS worker's own key (the runner's authenticated
# loopback self-calls to /simulate/* sign with the worker identity —
# mini-services/worker/control-auth.ts allowlists iss fayanms:worker and
# verifies against this same list, so self-trust is mandatory).
FAYANMS_SERVICE_PRIVATE_KEY="${worker.privateSingleLine}"
FAYANMS_SERVICE_PUBLIC_KEYS="${worker.publicBase64},${control.publicBase64}"

# Config snapshot KEK must match the app plane (same envelope)
FAYANMS_CONFIG_ENC_KEY="${configKek}"
FAYANMS_CONFIG_ENC_KEY_ID=k1

`;

mkdirSync(join(PROJECT, "mini-services", "worker"), { recursive: true });
writeFileSync(APP_ENV, appEnv, { mode: 0o600 });
writeFileSync(WORKER_ENV, workerEnv, { mode: 0o600 });

// Cross-verification printout (public material only — safe for logs)
console.log("✅ provisioned:");
console.log("   .env                     CONTROL private key + WORKER public key:", control.publicBase64.slice(0, 12) + "… trusts worker " + worker.publicBase64.slice(0, 12) + "…");
console.log("   mini-services/worker/.env WORKER private key + CONTROL public key:", worker.publicBase64.slice(0, 12) + "… trusts control " + control.publicBase64.slice(0, 12) + "…");
console.log("   FAYANMS_WORKER_NONCE_SALT entropy check:", randomBytes(4).toString("hex"));
