/**
 * Brand asset validation (Phase B3, plan §34). Run: `bun run brand:validate`
 *
 * FAILS when:
 *  - a required brand master (per src/lib/brand/identity.ts) is missing;
 *  - layout metadata references an external http/https logo (BRAND-001);
 *  - a brand/runtime SVG is missing a viewBox;
 *  - a runtime icon (public/icons/fayanms) hardcodes colors — masters must
 *    be colorless/currentColor (color contract, docs/brand/ICONOGRAPHY.md);
 *  - an icon filename attempts path traversal / invalid characters;
 *  - public/logo.svg (legacy compat path) contains animation;
 *  - generated app icons or social images are missing (run brand:raster);
 *  - a file-based metadata component (apple-icon/og/twitter) is missing.
 */
import { readdirSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const BRAND_DIR = join(ROOT, "public", "brand");
const ICONS_DIR = join(ROOT, "public", "icons", "fayanms");

let failures = 0;
const fail = (msg: string) => {
  failures++;
  console.error(`✗ ${msg}`);
};
const ok = (msg: string) => console.log(`✓ ${msg}`);

// 1. Required brand masters — keep in sync with FAYANMS_BRAND.assets.
const REQUIRED_MASTERS = [
  "fayanms-mark.svg",
  "fayanms-mark-mono.svg",
  "fayanms-mark-white.svg",
  "fayanms-wordmark.svg",
  "fayanms-wordmark-white.svg",
  "fayanms-lockup-horizontal.svg",
  "fayanms-lockup-horizontal-white.svg",
  "fayanms-lockup-stacked.svg",
  "fayanms-noc-mark.svg",
  "fayanms-network-shield.svg",
  "README.md",
];
for (const f of REQUIRED_MASTERS) {
  if (existsSync(join(BRAND_DIR, f))) ok(`brand master ${f}`);
  else fail(`missing brand master public/brand/${f}`);
}

// 2. No external logo in app metadata (BRAND-001 regression guard).
const layout = readFileSync(join(ROOT, "src", "app", "layout.tsx"), "utf8");
if (/icons:\s*\{[^}]*https?:\/\//.test(layout)) {
  fail("layout.tsx references an external http(s) icon URL (BRAND-001)");
} else {
  ok("layout metadata uses local file-based icons only");
}

// 3. File-based metadata components present.
for (const f of [
  "icon.svg",
  "favicon.ico",
  "apple-icon.tsx",
  "opengraph-image.tsx",
  "twitter-image.tsx",
  "manifest.ts",
]) {
  if (existsSync(join(ROOT, "src", "app", f))) ok(`metadata file ${f}`);
  else fail(`missing src/app/${f}`);
}

// 4. Raster derivatives exist (generated by scripts/generate-brand-raster-assets.ts).
for (const f of [
  "app-icon-192.png",
  "app-icon-512.png",
  "app-icon-maskable-192.png",
  "app-icon-maskable-512.png",
  "github-social-preview.png",
]) {
  if (existsSync(join(BRAND_DIR, f))) ok(`raster asset ${f}`);
  else fail(`missing ${f} — run: bun run brand:raster`);
}

// 5. Every SVG (brand + runtime icons) has a viewBox; runtime icons obey the
//    color contract; filenames are sane.
const NAME_RE = /^[a-z0-9-]+\.svg$/;
const COLOR_ATTR = /(fill|stroke)="(?!none|currentColor|rgba?\(0[^)]*\)|#FFF|#fff)[^"]*"/;

for (const dir of [BRAND_DIR, ICONS_DIR]) {
  const isRuntime = dir === ICONS_DIR;
  const files = readdirSync(dir).filter((f) => f.endsWith(".svg"));
  for (const f of files) {
    const p = join(dir, f);
    const svg = readFileSync(p, "utf8");
    if (!/viewBox="/.test(svg)) fail(`${isRuntime ? "icons/" : "brand/"}${f}: missing viewBox`);
    if (isRuntime) {
      if (!NAME_RE.test(f))
        fail(`icons/${f}: invalid name (kebab-case [a-z0-9-] only, no traversal)`);
      // Brand marks inside the runtime set (fayanms-mark etc.) keep
      // currentColor too; flag any hardcoded palette color.
      const body = svg.replace(/<svg[^>]*>/, "");
      const attrViolations = body.match(/(fill|stroke)="[^"]*"/g) ?? [];
      const bad = attrViolations.filter(
        (a) => !/="none"|="currentColor"/.test(a)
      );
      if (bad.length > 0)
        fail(`icons/${f}: hardcoded colors ${bad.slice(0, 3).join(", ")} — masters must be currentColor`);
      if (!/stroke="currentColor"/.test(svg))
        fail(`icons/${f}: stroke="currentColor" contract violated`);
    }
    if (/<animate|@keyframes|\.z-breathe/.test(svg))
      fail(`${f}: master SVG contains animation (do-not rule)`);
  }
  ok(
    `${isRuntime ? "runtime icons" : "brand masters"}: ${files.length} SVGs checked (viewBox${isRuntime ? " + color contract" : ""})`
  );
}

// 6. Legacy public/logo.svg must be the static canonical mark.
const logo = readFileSync(join(ROOT, "public", "logo.svg"), "utf8");
if (/<animate|@keyframes|z-breathe/.test(logo)) {
  fail("public/logo.svg is animated — replace with the canonical static mark (BRAND-004)");
} else {
  ok("public/logo.svg static (canonical mark)");
}

if (failures > 0) {
  console.error(`\nbrand:validate FAILED — ${failures} issue(s)`);
  process.exit(1);
}
console.log("\nbrand:validate passed.");
